config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :application, only: [:index]

  resources :sales do
    resources :comments  
  end

  root 'sales#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :sale
  belongs_to :user
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	belongs_to :user
	has_many :comments

	validates_presence_of :image_path, :message => "Put some image path!"
	validates_presence_of :title, :message => "Put some title!"
	validates_presence_of :content, :message => "Put some content!"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :sales
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #Página sobre o site
  def index
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	#Cria o comentário
	def create
		@sale = Sale.find(params[:sale_id])
		@comment = @sale.comments.create(params[:comment].permit(:comment))
		@comment.user_id = current_user.id if current_user
		@comment.save

		if @comment.save
			redirect_to sale_path(@sale)
		else
			render 'new'
		end
	end

	#Edita o comentário
	def edit
		@sale = Sale.find(params[:sale_id])
		@comment = @sale.comments.find(params[:id])
	end

	#Edita o comentário
	def update
		@sale = Sale.find(params[:sale_id])
		@comment = @sale.comments.find(params[:id])
		
		if @comment.update(params[:comment].permit(:comment))
			redirect_to sale_path(@sale)
		else
			render 'edit'
		end
	end

	#Deleta o comentário
	def destroy
		@sale = Sale.find(params[:sale_id])
		@comment = @sale.comments.find(params[:id])
		@comment.destroy
		redirect_to sale_path(@sale)
	end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
	before_action :find_sale, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	#Página Principal
	def index
		@sales = Sale.all.order("created_at DESC")
	end

	#Mostra a Promoção
	def show
	end

	#Cria uma nova promoção
	def new
		@sale = current_user.sales.build
	end

	#Cria uma nova promoção
	def create
		@sale = current_user.sales.build(sale_params)

		if @sale.save
			redirect_to @sale
		else
			render 'new'
		end
	end

	#Edita a promoção
	def edit
	end

	#Edita a promoção
	def update
		if @sale.update(sale_params)
			redirect_to @sale
		else
			render 'edit'
		end
	end

	#Deleta a promoção
	def destroy
		@sale.destroy
		redirect_to root_path
	end

	private

	#Encontra a promoção pelo ID correto
	def find_sale
		@sale = Sale.find(params[:id])
	end

	#Puxa os parâmetros do construtor
	def sale_params
		params.require(:sale).permit(:title, :content, :image_path)
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/application/index.html.erb
<center><h1><b>
<font size="8">About Us</font></b></h1></center>
<style type="text/css">
	#tb-0 {
	    margin-right: 30%;
	    margin-left: 0%;
	  }
	#tb-1 {
	    margin-left: 27%;
	    margin-right: -1%;
	  }
 </style>

 <br><br><br><br>
 <div id="tb-0">
	 <style type="text/css">
	.tg  {border-collapse:collapse;border-spacing:0;}
	.tg td{font-size:14px;padding:14px 18px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
	.tg th{font-size:14px;font-weight:normal;padding:14px 18px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
	.tg .tg-gbjd{font-weight:bold;font-size:18px;background-color:#808080;color:#D3D3D3;text-align:center}
	.tg .tg-qems{background-color:#808080;color:#D3D3D3;text-align:center}
	@media screen and (max-width: 767px) {.tg {width: auto !important;}.tg col {width: auto !important;}.tg-wrap {overflow-x: auto;-webkit-overflow-scrolling: touch;}}</style>
	<div class="tg-wrap"><table class="tg">
	  <tr>
	    <th class="tg-gbjd">PercentOff - Sales is an web site developed for people to share sales and creates a community in which the motto is to save money. Here
you can share and see the newests sales all around the country and enjoy it to save some money to the hard days!
What are you waiting for? Find and Share the best deals with our community! Join us today! It's Free!!!</th>
	    <th class="tg-qems"><%= image_tag('LogoContorno.png', size: '310x280') %></th>
	  </tr>
	</table></div>
 </div>

 <br><br><br>
 <div id="tb-1">
	<style type="text/css">
	.tg  {border-collapse:collapse;border-spacing:0;}
	.tg td{font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
	.tg th{font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
	.tg .tg-cq0p{font-weight:bold;font-size:18px;background-color:#808080;color:#d3d3d3;text-align:center}
	@media screen and (max-width: 767px) {.tg {width: auto !important;}.tg col {width: auto !important;}.tg-wrap {overflow-x: auto;-webkit-overflow-scrolling: touch;}}</style>
	<div class="tg-wrap"><table class="tg">
	  <tr>
	    <th class="tg-cq0p"><%= image_tag('Allan.jpeg', size: '280x300') %></th>
	    <th class="tg-cq0p">Software Engineering Student at Universidade de Brasilia - Faculdade do Gama. One of the main developer of the PercentOff website.
Uses to play lolzinho with the friends in the idle hours (almost never).</th>
	  </tr>
	</table></div>
 </div>

 <br><br><br>
 <div id="tb-0">
 	 <style type="text/css">
	.tg  {border-collapse:collapse;border-spacing:0;}
	.tg td{font-size:14px;padding:14px 18px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
	.tg th{font-size:14px;font-weight:normal;padding:14px 18px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
	.tg .tg-gbjd{font-weight:bold;font-size:18px;background-color:#808080;color:#D3D3D3;text-align:center}
	.tg .tg-qems{background-color:#808080;color:#D3D3D3;text-align:center}
	@media screen and (max-width: 767px) {.tg {width: auto !important;}.tg col {width: auto !important;}.tg-wrap {overflow-x: auto;-webkit-overflow-scrolling: touch;}}</style>
	<div class="tg-wrap"><table class="tg">
	  <tr>
	    <th class="tg-gbjd">Software Engineering Student at Universidade de Brasilia - Faculdade do Gama. One of the main developer of the PercentOff website.
Uses to sleep in the idle hours (almost never).</th>
	    <th class="tg-qems"><%= image_tag('Hugo.jpeg', size: '280x300') %></th>
	  </tr>
	</table></div>
 </div>
 <br><br><br><br>

app/views/comments/_comment.html.erb
<% if comment.user != nil %>
	<ul><li>
	<div><b><%= comment.comment %></b><p>- Posted by 
	<%= comment.user.email %></div>
	<% if ((comment.user == current_user) || current_user.try(:admin?)) %>
		<font color="black"><%= button_to "Edit", edit_sale_comment_path(comment.sale, comment), :method => :get %></font>
		<font color="black"><%= button_to "Delete", [comment.sale, comment], method: :delete, data: {confirm: "Are you sure you want to do this?"} %></font>
	<% end %></p>
	</ul></li>
<% else %>	
	<% comment.destroy %>
	<% $contador = @sale.comments.count - 1 %>
<% end %>

app/views/comments/_form.html.erb
<% if user_signed_in? %>
	<h3><b>Write about it:</b></h3> 
    <%= form_for ([@sale, @sale.comments.build]) do |f| %>
		<h4><%= f.text_area(:comment, size: '110x4') %></h4><br>
		<br>
		<h4><%= f.submit %><br></h4>
	<%end%>
<% end %>

app/views/comments/edit.html.erb
<%= form_for ([@sale, @comment]) do |f| %>
	<br><br>
	<h4><%= f.text_area(:comment, size: '110x4') %></h4><br>
	<h4><%= f.submit %></h4><br>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  
  <title>Percent Off - Sales</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link href="http://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

  <style>

  body {
    font: 400 15px Lato, sans-serif;
    line-height: 1.8;
    color: #DCDCDC;
  }

  h2 {
    font-size: 24px;
    text-transform: uppercase;
    color: #DCDCDC;
    font-weight: 600;
    margin-bottom: 30px;
  }

  h4 {
    font-size: 18px;
    line-height: 1.375em;
    color: #303030;
    font-weight: 400;
    margin-bottom: 30px;
  }
    
  #wrapper {
    margin-left: 3%;
    margin-right: 3%;
  }

  .container-fluid {
    padding: 60px 50px;
  }

  .navbar {
    margin-bottom: 0;
    background-color: rgba(128,128,128,0.5);
    z-index: 9999;
    border: 0;
    font-size: 18px !important;
    line-height: 1.42857143 !important;
    letter-spacing: 3.5px;
    border-radius: 0;
    font-family: Montserrat, sans-serif;
  }
  .navbar li a, .navbar .navbar-brand {
    color: #fff !important;
  }
  .navbar-nav li a:hover, .navbar-nav li.active a {
    color: #000 !important;
    background-color: #fff !important;
  }
  .navbar-default .navbar-toggle {
    border-color: transparent;
    color: #fff !important;
    }

  </style>
</head>

<body background = "http://www.pixelstalk.net/wp-content/uploads/2016/04/Wallpapers-HD-grey-pictures-images-desktop.jpg" id="percentOff" data-spy="scroll" data-target=".navbar" data-offset="60">

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
        <%= link_to image_tag('NomeComLogo.png', :size => "190x60"), root_path %> 
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to "About Us", application_index_path %></li>
        <% if user_signed_in? %>
            <li><%= link_to "New Sale", new_sale_path %></li>
            <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>        
        <% else %>
            <li><%= link_to "Join us", new_user_registration_path %></li>
            <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %> 

      </ul>
    </div>
  </div>
</nav>
    
<div id="wrapper">
    <br><br>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>    
    <%= yield %>
</div>
<br><br><br><br>
<center> <%= link_to image_tag('NomeComLogo.png'), application_index_path %> </center>

<footer class="container-fluid text-center">
  <a href="" title="To Top">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>
  <p>Powered by <a href="http://www.ece.rice.edu/~wakin/images/lenaTest3.jpg" target="_blank" title="lena">Allan, Hugo and Lena</a></p>
</footer>

</body>
</html>

<%= javascript_include_tag "aplication" %>

app/views/sales/_form.html.erb
<center>
<%= form_for @sale do |f| %>
	<%= f.label :title %><br>
	<h4><%= f.text_field(:title, size: '85') %><br></h4>
	<br> 
	<%= f.label :content %><br>
	<center><h4><%= f.text_area(:content, size: '118x10') %></h4><br></center>
	<br>
	<%= f.label :image_path %><br>
	<h4><%= f.text_field(:image_path, size: '85') %></h4><br>
	<br>
	<h4><%= f.submit %><br></h4>
<%end%>
</center>

app/views/sales/edit.html.erb
<br><center><h1><b> Edit Sale </b></h1><br><br>

<%= render 'form' %>

<%= link_to "Cancel", sale_path %>
</center>

app/views/sales/index.html.erb
<center>
<% @sales.each do |sale| %>
	<% if sale.user == nil %>
		<% sale.destroy %>
	<% else %>	
		<br>
		<style type="text/css">
		.tg  {border-collapse:collapse;border-spacing:0;border: hidden;}

		.tg td{font-size:15px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border: hidden;}
		.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border: hidden;}
		.tg .tg-m3ox{font-size:16px;background-color:#efefef;color:#656565;vertical-align:top}
		.tg .tg-dakb{font-size:27px;background-color:#efefef;color:#696969;text-align:center}
		.tg .tg-8nuy{font-size:16px;background-color:#efefef;color:#656565}
		.tg .tg-j4kc{background-color:#efefef;text-align:center}
		.tg .tg-tezs{font-size:17px;background-color:#efefef;color:#000000}
		@media screen and (max-width: 767px) {.tg {width: auto !important;}.tg col {width: auto !important;}.tg-wrap {overflow-x: auto;-webkit-overflow-scrolling: touch;}}
		</style>
		<div class="tg-wrap"><table class="tg">
		  <tr>
		    <th class="tg-dakb" colspan="2"><b><%= sale.title %></b></th>
		  </tr>
		  <tr>
		    <td class="tg-8nuy"><b>Published at <%= time_ago_in_words(sale.created_at) %> ago by <%= sale.user.email %></b></td>
		    <td class="tg-j4kc" rowspan="3"><%= link_to image_tag(sale.image_path, :size => "280x280"), sale %></td>
		  </tr>
		  <tr>
		    <td class="tg-tezs"><b><%= truncate(sale.content, :length => 300) %><%= link_to "Read more...", sale  %></b></td>
		  </tr>
		  <tr>
		    <td class="tg-m3ox"><b><%= sale.comments.count %>  Comments</b></td>
		  </tr>
		</table></div>
		<br>
	<% end %>
<% end %>
</center>

app/views/sales/new.html.erb
<br><center><h1><b> New Sale </b></h1></center><br><br>

<%= render 'form' %>

app/views/sales/show.html.erb
<center><br><h1><b><%= @sale.title %></b></h1>
<div>
	<br><br><%= @sale.content %><br><br><br>
	<%= image_tag(@sale.image_path) %>
	<br><br>

	<% if ((@sale.user == current_user) || current_user.try(:admin?)) %>
		<font color="black"><%= button_to "Edit", edit_sale_path(@sale), :method => :get %></font>
		<font color="black"><%= button_to "Delete", sale_path(@sale), method: :delete, data: { confirm: "Are you sure you want to do this?"}%></font>
	<% end %>

</div>
</center>

<br>
<% $contador = @sale.comments.count  %>
<h3><b> <%= $contador %>  Comments: </b></h3> 
<%= render @sale.comments %>
<br>
<%= render "comments/form" %>
<br>

app/views/users/shared/_links.html.erb
<center>
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>
</center>